[2022-11-28T11:42:38.450+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.transform manual__2022-11-28T11:42:08.324246+00:00 [queued]>
[2022-11-28T11:42:38.508+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.transform manual__2022-11-28T11:42:08.324246+00:00 [queued]>
[2022-11-28T11:42:38.512+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T11:42:38.514+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-28T11:42:38.514+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T11:42:38.585+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform> on 2022-11-28 11:42:08.324246+00:00
[2022-11-28T11:42:38.627+0000] {standard_task_runner.py:55} INFO - Started process 1421 to run task
[2022-11-28T11:42:38.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_try_oop', 'transform', 'manual__2022-11-28T11:42:08.324246+00:00', '--job-id', '572', '--raw', '--subdir', 'DAGS_FOLDER/dag_try_oop.py', '--cfg-path', '/tmp/tmpqfoxnsqu']
[2022-11-28T11:42:38.679+0000] {standard_task_runner.py:83} INFO - Job 572: Subtask transform
[2022-11-28T11:43:07.356+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
[2022-11-28T11:43:07.858+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
